# Generated by Django 4.2.3 on 2024-05-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipboard', '0002_alter_clipboard_id_alter_clipboarditem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipboard',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
