# Generated by Django 4.2.4 on 2024-06-03 16:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clipboard', '0003_alter_clipboard_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipboard',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
